import { Inter, Jost } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const font = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Nav />
        <div className="bg-gray-200 pb-10">{children}</div>
        {/* Footer */}
        <div className="flex justify-center items-center bg-black py-5">
          <p className="text-white font-bold text-2xl">
            Global Engineering Academy
          </p>
        </div>
      </body>
    </html>
  );
}
